name: CI

on: push

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
      env:
        CREFO_USERACCOUNT: ${{ secrets.CREFO_USERACCOUNT }}
        CREFO_GENERALPASSWORD: ${{ secrets.CREFO_GENERALPASSWORD }}
        CREFO_INDIVIDUALPASSWORD: ${{ secrets.CREFO_INDIVIDUALPASSWORD }}
        CREFO_CLIENTAPPLICATIONNAME: ${{ secrets.CREFO_CLIENTAPPLICATIONNAME }}
